steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}'
      - '-f'
      - 'api/Dockerfile'
      - '.'
    timeout: 600s

  # Push to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_NAME}'

images:
  - '${_IMAGE_NAME}'

timeout: 1200s
